steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/img-classifier-001/streamlit_app:v2', '.']
  timeout: 180s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/img-classifier-001/streamlit_app:v2']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    ls -la
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=K8s/
  - --location=europe-central2
  - --cluster=mykube
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
