steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/img-classifier-001/myapp:v1', '.']
  timeout: 180s
options:
  logging: GCS_ONLY
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/img-classifier-001/myapp:v1']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: "bash"
  args:
  - "-c"
  - |
    echo "Docker Container Built"
    ls -la
    ls -al models/
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=K8s/
  - --location=europe-central2
  - --cluster=mykube
